# Generated by Django 2.1.7 on 2019-03-26 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=48)),
                ('author', models.CharField(max_length=4096)),
                ('year', models.IntegerField(max_length=4)),
                ('status', models.CharField(choices=[('available', 'Availabe'), ('checked-out', 'Checked-Out')], default='available', max_length=48)),
            ],
        ),
    ]
