# Generated by Django 2.1.7 on 2019-03-26 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books_app', '0002_auto_20190326_2329'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='last_borrowed',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='year',
            field=models.IntegerField(),
        ),
    ]
