# Generated by Django 2.1.7 on 2019-03-27 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books_app', '0003_auto_20190326_2332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='date_added',
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='last_borrowed',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
