# Generated by Django 2.1.7 on 2019-03-27 21:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('books_app', '0005_auto_20190327_0035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='date_added',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
